linters:
  Indentation:
    enabled: true
  IdSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  Comment:
    enabled: false
